# Generated by Django 5.0.6 on 2024-05-14 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('info', models.TextField(verbose_name='Information')),
                ('price', models.FloatField(verbose_name='Price')),
                ('status', models.CharField(choices=[('done', 'Заказано'), ('none', 'Заказать'), ('delivering', 'Доставляеться'), ('cooking', 'Готовиться'), ('accepted', 'Принят'), ('none', 'none')], max_length=30, verbose_name='Status:')),
            ],
        ),
        migrations.CreateModel(
            name='DishImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_image/', verbose_name='Image:')),
            ],
        ),
        migrations.CreateModel(
            name='Connect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dish', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='main.dish')),
            ],
        ),
        migrations.AddField(
            model_name='dish',
            name='images',
            field=models.ManyToManyField(to='main.dishimage', verbose_name='Images'),
        ),
    ]
