# Generated by Django 5.0.6 on 2024-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Кол-во:'),
            preserve_default=False,
        ),
    ]
