# Generated by Django 5.0.6 on 2024-05-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dish_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='quantity',
            field=models.IntegerField(blank=True, verbose_name='Кол-во:'),
        ),
    ]
