# Generated by Django 5.0.6 on 2024-05-16 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_dish_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='dish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.dish'),
        ),
    ]
