# Generated by Django 5.0.6 on 2024-05-16 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_connect_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='kind',
            field=models.CharField(choices=[('soda', 'Напитки'), ('desert', 'Десерты'), ('first', 'Первое'), ('salat', 'Салаты'), ('sec', 'Второе'), ('fast', 'Фаст-фуд'), ('alco', 'Алкоголь'), ('tuck', 'Закуски')], default=1, max_length=30, verbose_name='Type:'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dish',
            name='status',
            field=models.CharField(choices=[('done', 'Заказано'), ('none', 'Заказать'), ('delivering', 'Доставляеться'), ('cooking', 'Готовиться'), ('accepted', 'Принят')], max_length=30, verbose_name='Status:'),
        ),
    ]
