# Generated by Django 5.0.6 on 2024-05-18 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_dish_kind_alter_dish_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='images',
        ),
        migrations.AddField(
            model_name='dishimage',
            name='dishes',
            field=models.ManyToManyField(to='main.dish', verbose_name='Dishes:'),
        ),
    ]
