# Generated by Django 5.0.6 on 2024-05-25 08:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_dish_images_dishimage_dishes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.IntegerField(max_length=16, validators=[django.core.validators.MinLengthValidator(16)], verbose_name='Card-number')),
                ('cvc', models.IntegerField(max_length=3, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='CVC')),
                ('date', models.DateField(verbose_name='Date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
