# Generated by Django 5.0.6 on 2024-05-28 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Price'),
            preserve_default=False,
        ),
    ]
