# Generated by Django 5.0.6 on 2024-05-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во:'),
        ),
    ]
