# Generated by Django 5.0.6 on 2024-06-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_connect_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='status',
        ),
        migrations.AddField(
            model_name='connect',
            name='status',
            field=models.CharField(choices=[('done', 'Заказано'), ('none', 'Заказать'), ('delivering', 'Доставляеться'), ('cooking', 'Готовиться'), ('accepted', 'Принят')], default=1, max_length=30, verbose_name='Status:'),
            preserve_default=False,
        ),
    ]
